name: ci

on: pull_request
jobs:
    test:
        runs-on: ubunto-latest

        steps:
            - name: primeira CI nossa
              run: echo hello world

            - name: O que tem aqui
              run: echo $(ls)

            - name: qual diretorio
              run: echo $(pwd)
